apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projet-final-ingress
  namespace: projet-final
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: projet-final.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: back-svc
                port:
                  number: 8000

          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: front-svc
                port:
                  number: 80
