name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test-back:
    name: Tests backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: app/back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (pytest)
        working-directory: app/back
        run: pytest

  build-and-push:
    name: Build & push Docker images
    runs-on: ubuntu-latest
    needs: test-back
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./app/back
          push: true
          tags: |
            magickblack33/final-project:back
            magickblack33/final-project:back-${{ github.sha }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./app/front
          push: true
          tags: |
            magickblack33/final-project:front
            magickblack33/final-project:front-${{ github.sha }}
